// Book data used across the site
const books = [
  {
    id: 1,
    title: "Introduction to Algorithms",
    author: "Thomas H. Cormen",
    category: "Computer Science",
    image: "https://pictures.abebooks.com/isbn/9780070131514-uk.jpg",
  },
  {
    id: 2,
    title: "Operating System Concepts",
    author: "A. Silberschatz",
    category: "Computer Science",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSt6x9t6TjEc39iNOjbZeFM-K9eiv4o8IVl-w&s",
  },
  {
    id: 3,
    title: "Computer Networks",
    author: "Andrew S. Tanenbaum",
    category: "Computer Science",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT1WfC7Q2VAG4IcV8gceRa54aN35SEgQRZjFA&s",
  },
  {
    id: 4,
    title: "Clean Code",
    author: "Robert C. Martin",
    category: "Computer Science",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQi3QVc827UwdPIt8He9iqiK2zCX9kdAdMSnQ&s",
  },
  {
    id: 5,
    title: "A Brief History of Time",
    author: "Stephen Hawking",
    category: "Science",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRR7peDWE9yftsDsE_RDMo-D2cgrt0x4rMseg&s",
  },
  {
    id: 6,
    title: "Sapiens",
    author: "Yuval Noah Harari",
    category: "History",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQnPdJ2sEuyuo-EAcze5x9T6_Lwpu6Vq33pMA&s",
  },
  {
    id: 7,
    title: "To Kill a Mockingbird",
    author: "Harper Lee",
    category: "Fiction",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT7ZilepQgxRuKxMSyhrYU8NNTPK1dRPJkEVQ&s",
  },
  {
    id: 8,
    title: "Steve Jobs",
    author: "Walter Isaacson",
    category: "Biography",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSiMkHPkjx9bT3ocUt8Vyz4r6zlphHq2kd09Q&s",
  },
  {
    id: 9,
    title: "Artificial Intelligence: A Modern Approach",
    author: "Stuart Russell",
    category: "Computer Science",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ5w4KnNAnyhdMvElvSxy9RjvZ_7tYvwfKSKA&s",
  },
  {
    id: 10,
    title: "Database System Concepts",
    author: "Abraham Silberschatz",
    category: "Computer Science",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRr-XKkkZAxW9t0ksfugW7HIdPN1KzgGw33cQ&s",
  },
  {
    id: 11,
    title: "The Pragmatic Programmer",
    author: "Andrew Hunt",
    category: "Computer Science",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSoOjitkXEt896ZSs0BqUwe4XI6k7iNClfr9Q&s",
  },
  {
    id: 12,
    title: "Deep Work",
    author: "Cal Newport",
    category: "Biography",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQsdIVOHttaA2KcZ3CTFHJl0g9NQVI7Nteunw&s",
  },
  {
    id: 13,
    title: "Cosmos",
    author: "Carl Sagan",
    category: "Science",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQwcaF4VuzzBH2PdlS36Wg49mxNhwvLw7_NSA&s",
  },
  {
    id: 14,
    title: "The Selfish Gene",
    author: "Richard Dawkins",
    category: "Science",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR_j0rvKgoh3LxE6NRLdbFH8jzKWJqLgLY0-w&s",
  },
  {
    id: 15,
    title: "1984",
    author: "George Orwell",
    category: "Fiction",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT0tHx_wY13We-evHdpoYSut77GYP8wOiG5jA&s",
  },
  {
    id: 16,
    title: "The Great Gatsby",
    author: "F. Scott Fitzgerald",
    category: "Fiction",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRnyBFVzEq81r-7JhxT4irQpQ5IucpmmYaTlw&s",
  },
  {
    id: 17,
    title: "Guns, Germs, and Steel",
    author: "Jared Diamond",
    category: "History",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTppDhnmUYjO3ITZceyZZeaICM6MQ1e-pssrg&s",
  },
  {
    id: 18,
    title: "The Wright Brothers",
    author: "David McCullough",
    category: "History",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSWNhyRqotdq9aCeP66oZvMssSMj-w7IECHPQ&s",
  },
  {
    id: 19,
    title: "Long Walk to Freedom",
    author: "Nelson Mandela",
    category: "Biography",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTRmT3ymhHJnuVIEgk50EIkbJ4MCYj4bYSPZQ&s",
  },
  {
    id: 20,
    title: "The Innovators",
    author: "Walter Isaacson",
    category: "Biography",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQISefJcvoPj48KCysM6h2m-B5ftv6VMsUazg&s",
  },
];

// Category list for filters
const categories = ["All", "Computer Science", "Fiction", "History", "Science", "Biography"];
